CC=gcc

all: runall.o unity.o unity_fixture.o movie_tests.o

runall.o:
	$(CC) -c runall.c -o ../build/runall.o

unity.o:
	$(CC) -c ../../unity/unity.c -o ../build/unity.o

unity_fixture.o:
	$(CC) -c ../../unity/unity_fixture.c -o ../build/unity_fixture.o

movie_tests.o:
	$(CC) -c movie_tests.c -o ../build/movie_tests.o
