CC=gcc

all: runall.o counter_tests.o unity.o unity_fixture.o

runall.o:
	$(CC) -c runall.c -o ../build/runall.o

counter_tests.o:
	$(CC) -c counter_tests.c -o ../build/counter_tests.o

unity.o:
	$(CC) -c ../../unity/unity.c -o ../build/unity.o

unity_fixture.o:
	$(CC) -c ../../unity/unity_fixture.c -o ../build/unity_fixture.o
